logging:
    level:
        org:
            hibernate:
                SQL: debug
spring:
    datasource:
#        initialization-mode: always
        password: rootroot
        url: jdbc:mysql://localhost:3306/travelplanner?createDatabaseIfNotExist=true

        username: root
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    flyway:
        locations: classpath:/db/migrations